export enum RoomTypeEnum {
  SINGLE_ONE_BED = 'SINGLE_ONE_BED',
  SINGLE_TWO_BEDS = 'SINGLE_TWO_BEDS',
  SINGLE_THREE_BEDS = 'SINGLE_THREE_BEDS',
  SUITE_ONE_BIG_BED = 'SUITE_ONE_BIG_BED',
  SUITE_BIG_AND_SMALL_BED = 'SUITE_BIG_AND_SMALL_BED',
}
